<a href="https://colab.research.google.com/github/anjali1526/Numpy-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time
import numpy as np

In [ ]:
start = time.time()
numpy_arr= np.arange(1000000)
numpy_arr = numpy_arr**2
end = time.time()
numpy_time = end-start
print(f"Time taken: {numpy_time:.6f} seconds")

Time taken: 0.009126 seconds


In [ ]:
import time
start = time.time()
list1= list(range(1000000))
for i in list1:
    i*=i
end = time.time()
list_time = end-start
print(f"Time taken: {list_time:.6f} seconds")

Time taken: 0.322848 seconds


In [ ]:
speedup = list_time/numpy_time
print(speedup)

35.37696266687567


Creating numpy array
- from list

In [ ]:
hello =np.array([1,2,3])
print(hello)

[1 2 3]


Using built in functions
-np.zeros create an array with zeroes in it

In [ ]:
hi =np.zeros(3)
print(hi)

[0. 0. 0.]


In [ ]:
hey=np.ones(4)
print(hey)


[1. 1. 1. 1.]


In [ ]:
hm = np.random.random(3)
print(hm)

[0.38532376 0.57597693 0.63673241]


In [ ]:
ok = np.arange(1,6,3)
print(ok)

[1 4]


In [ ]:
okk = np.linspace(2,89,6)
print(okk)

[ 2.  19.4 36.8 54.2 71.6 89. ]


In [ ]:
arr= np.random.random(3)
print(arr.shape)

(3,)


In [ ]:
arr= np.array([1,2,3])
arr= arr 2
print(arr)


SyntaxError: invalid syntax (3589616593.py, line 2)

In [ ]:
a = np.array([[1,2,3], [5,6,9]])
print(a)

[[1 2 3]
 [5 6 9]]


In [ ]:
b = np.zeros((2,2))
print(b)

[[0. 0.]
 [0. 0.]]


In [ ]:
c = np.arange(1,7).reshape(2,3)
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
d=np.zeros((2, 4, 3))
print(d)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
